### ISSUE TITLE
variables declared with `my` lead to errors

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#1024]
Load this problem in the editor:

```
DOCUMENT();
loadMacros(qw(PGstandard.pl PGML.pl));

my $m = 5;

BEGIN_PGML
[_]{$m}
END_PGML

ENDDOCUMENT();
```

and after rendering it, click to show correct answers. I get an error:
```

    ------
    No answer evaluator for the question labeled: AnSwEr0001
    ------
    Answer evaluator AnSwEr0001 was not executed due to errors.
    ========

```

Removing the `my`, this goes away. I ended up with a `my` declaration in a problem file from some copy-pasting. I normally wouldn't use `my` otherwise. And I was getting these errors. It took me a while to work out that the source of the errors was somehow the `my`. Am I wrong to assume that `my` declared variables should still work in a PG problem?

FWIW, I see this in both 2.18 and develop.

**Comment by drgrice1** [comment]
I have also done this by accident (actually because I have now ingrained the good practice of doing so in regular perl files).  The problem is that by using `my` it gives the variable local scope.  Then when PGML runs that variable is not in its scope.

I am sorry to tell you this, but there is absolutely no way that this can be fixed.  The only way to fix this would be to rewrite Perl to do bad things, and that is really not a realistic possibility.
