### ISSUE TITLE
Two solutions using Context("Inequalities")

### ISSUE THREAD

**Issue by d-torrance** [openwebwork/pg#280]
Hello!

Consider the following problem:

    DOCUMENT();

    loadMacros(
      "PGstandard.pl",
      "MathObjects.pl",
      "contextInequalities.pl"
    );

    Context("Inequalities");

    $ans = Compute("x=1 or x=2");

    TEXT(beginproblem());
    BEGIN_TEXT
    \{ ans_rule(20) \}
    END_TEXT

    ANS($ans->cmp());

    ENDDOCUMENT();

The solution "{1,2}" is marked correct, but "x=1 or x=2" (which we used to define the answer in the first place) is marked incorrect.

This is an issue for many of the problems in [1].

[1] https://github.com/openwebwork/webwork-open-problem-library/tree/master/OpenProblemLibrary/CollegeOfIdaho/setAlgebra_04_03_AbsoluteValue

**Comment by dpvc** [comment]
The `x=1 or x=2` expression is supposed to produce a Set object equivalent to `{1,2}`, but it turns out that it is producing a Union object (with one element, the set `{1,2}`).  Due to some technical issues in how Union's are checked, this causes the correct answer to be marked incorrect.  It is easily fixed in the `lib/Value/Set.pm` file, but until that is is an official release, one way to handle it in the problem itself is to add

    $ans = $ans->{data}[0] if $ans->type eq "Union";  # hack to fix problem with inequality above

directly after the line that computes `$ans`.  That will fix it for now, and when the library is fixed, the `if` statement will be false, and it will stop doing anything.  So the problem should continue to work without modification (though it would be good to remove the hack eventually).

**Comment by dpvc** [comment]
The `issue280` branch of my fork of PG includes the fix.

**Comment by dpvc** [comment]
The branch has been merged into `develop`.
