### ISSUE TITLE
A cheat to the exact_no_trig

### ISSUE THREAD

**Issue by nurfnick** [openwebwork/pg#285]
A student told me that they were able to hack the no decimals by instead of entering .25 they enter 25*10^(-2).  Since it has no decimals it was excepted by the answer checker.

**Comment by dpvc** [comment]
Of course, they could have just entered `25/100`, which is allowed by `exact_no_trig`.  Of course, one could enter any "decimal" that way.  But I doubt that there is any reasonable way to avoid that, since fractions should be allowed in these answers.  You do want to allow things like `1/2`, etc.  So yes, you can enter that sort of answer and get credit for it.

**Comment by jwj61** [comment]
Since the given answer is exactly right, it is not troubling at all.  More on point would be a question which asks for sin(pi/4) and a student answers 7071067812*10^(-10).  But it does not seem worth worrying about given the likelihood of students doing that who don't know the actual answer to the question.  If they want to cheat the question, they are much more likely to use Wolfram alpha.
