### ISSUE TITLE
Matrix preview bug with open/closed symbols when using formulas.

### ISSUE THREAD

**Issue by somiaj** [openwebwork/pg#660]
When using a formula matrix, not all matrix TeX strings honor changing the open/closed symbols (similar to #627). In this case the TeX string and correct answer string do not use the determinant symbols:

```
DOCUMENT();
loadMacros(
   'PGstandard.pl',
   'PGML.pl',
);

Context('Matrix');
$A1 = Matrix([[Formula("x"),Formula("2x")],[Formula("3x"),Formula("4x")]]);
$A1->{open} = '|';
$A1->{close} = '|';
$A2 = Matrix([[5,6],[7,8]]);
$A2->{open} = '|';
$A2->{close} = '|';

BEGIN_PGML
+ [`[$A1]=`] [__]*{$A1}

+ [`[$A2]=`] [__]*{$A2}
END_PGML
ENDDOCUMENT();
```

![image](https://user-images.githubusercontent.com/18082412/156933522-30db44b8-8c92-4911-a702-d045d86aeb51.png)

**Comment by dpvc** [comment]
The issue, here, is that `$A1` isn't really what you think is.  MathObjects doesn't provide for a Matrix of Formulas, and when it encounters one, it converts it to a Formula returning a Matrix.  So `$A1` is actually a Formula object, not a Matrix object, and so setting the `open` and `close` properties of the object doesn't affect its output (the answer array is handle specially for a formula returning a matrix, and it appears the values were used there).

One solution would be to use

```
$A1->{tree}{open} = $A1->{tree}{close} = "|";
```

instead of (or perhaps in combination with) your current settings, which sets the open and close properties for the underlying matrix object.

**Comment by somiaj** [comment]
Thanks, that does indeed work. I thought it was something to do with how formula matrices work differently than normal matrices, but was confused why the answer array worked as expected.

Would this still be considered an issue? Maybe formula matrices can also inherit the open/closed symbols from the main math object like the ans_array does? If you don't consider it an issue, I will just close this.

**Comment by pstaabp** [comment]
@somiaj Okay if we close this?
