### ISSUE TITLE
MathQuill not functioning on Safari

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/pg#684]
It appears that the Mathquill is not behaving with the current version of safari (15.5) on MacOS 12.4.  It clearly worked sometime on previous versions and if anyone has safari before 15.5 it would be helpful to test.

If you load a problem and Mathquill is enabled, click in any of the answer inputs and the MathQuill operator/expression buttons (aka MathQuill toolbar) will appear on the right side. However, clicking on any of the button causes the toolbar to disappear and nothing is inserted in the answer input. 

I have tested on chrome and Mathquill works as expected and just tested Safari Technology Preview (aka beta) and works.  My hope would be that the next version of safari fixes whatever regression was introduced and we can close this.  If not, we may need a workaround.

**Comment by dlglin** [comment]
Could this be related to https://derflounder.wordpress.com/2022/05/18/safari-15-5-embedded-content-slow-to-load/?

**Comment by pstaabp** [comment]
I don't think so.  We've narrowed it down to a field (relatedTarget) in a `FocusEvent` that is null on safari, whereas on chrome, it is the correct value . Because of this the existing code hides the MathQuill toolbar.

**Comment by drgrice1** [comment]
Note that there was a change in the way that this worked from WeBWorK 2.16 to 2.17.  The previous method used a timeout hack.  I switched to the method of using the FocusEvent.RelatedTarget instead because it isn't a hack.  See https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget and https://w3c.github.io/uievents/#dom-focusevent-relatedtarget.

According to the MDN web docs the FocusEvent.RelatedTarget is supposed to be fully supported by all browsers.  Apparently Safari does not quite agree with that.

@pstaapb:  Can you test with WeBWorK 2.16, and see if this issue still happens there?  I guess I can revert the code to using the old hack if so.  Sigh...

**Comment by drgrice1** [comment]
@pstaabp:  Actually, rather than testing with ww 2.16, just test #685.

**Comment by pstaabp** [comment]
#685 works for me.

**Comment by taniwallach** [comment]
@pstaabp Since https://github.com/openwebwork/pg/pull/685 I think this can be closed.

**Comment by pstaabp** [comment]
#685 has been merged and #704 is ready as the original method if safari is stable enough to use it again.  Will close.
