### ISSUE TITLE
Should `A` stand for angstrom or ampere?

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#743]
In `Units.pm`, the unit `A` is for angstrom, 10e-10 meters. Also `amp` is one of the fundamental units.

I searched the OPL (OPL, Contrib, and Pending folders) and I found no problems at all that use either of the above units. My grep regex in the search was `WithUnits(.*\W\(A\|amp\)\W`, which I think was sufficient but maybe is not. It found a few instances like `NumberWithUnits("$A","hr");` but nothing with the `A` actually being used as a unit.

Of course any such regex is not 100% conclusive, if the unit is hidden in a variable.

Anyway, it seems to me that `A` is much more commonly used as the abbreviation for ampere. (That is how it was being thought of recently when a student entered an answer of `0 T m/A` and discovered a bug.)

Should we change the meaning of `A` to ampere? It feels 1000x more likely to be used by a student to mean ampere than to mean angstrom. If there is ever a WW exercise that needs angstrom, well first of all `A` is not even the right character for that. It should be `Å`. But second of all, that exercise with its context could be coded to override the meaning of `A`.

**Comment by pkohl** [comment]
If it doesn't break a bunch of things and isn't too hard to do, I'd be in favor of the change.  The SI symbol for the ampere is A (it's one of the seven SI base units), and I agree that it is much more likely for end users to mean ampere than angstrom if they put in that symbol.  

That said, it's also not that hard to work around if changing the symbol would break things.

**Comment by duffee** [comment]
I also think `A` should stand for ampere.

The only references to Angstroms in the OPL are help files:
- OpenProblemLibrary/macros/FortLewis/AnswerFormatHelp.pl
- OpenProblemLibrary/Michigan/units.html

The question is whether you want a gradual transition or you like the Big Bang approach.

Either way, the first step is to add the new unit for Angstrom to Units.pm so that the help files in WW and OPL can be updated when the new unit is available in production.

I've just opened PR #753 to add some new units.  The new angstrom could be added to that PR for convenience or separated out in its own PR for faster merging to main.

**Comment by pstaabp** [comment]
We've merged in some changes (listed above) to handle angstroms.
