### ISSUE TITLE
Variable adjacent to code substitution in TEXT causes hardcopy error.

### ISSUE THREAD

**Issue by Alex-Jordan** [openwebwork/pg#912]
The following could be old, and could be expected behavior to WW developers. But it is unexpected behavior for problem authors. 

Try this MWE:

```
DOCUMENT();
loadMacros("PGstandard.pl");
BEGIN_TEXT

$DOLLAR\{ ans_rule(1) \}

END_TEXT
ANS(Real(1)->cmp);
ENDDOCUMENT();
```

and build hardcopy, and it fails. The tex file it creates is:

```
\batchmode
\documentclass{article}
\usepackage{webwork2}
\pagestyle{empty}
\parindent=0pt
\begin{document}

\newpage
{\bf (Error: syntax error  in '
$DOLLAR{\\answerRule[AnSwEr0001]{3}}

')}

\vspace{\baselineskip}\par{\small{\it Correct Answers:}
\begin{itemize}
\item
$\displaystyle 1$
\end{itemize}}\par

\end{document}
```

Note this is not about dollar signs in tex. You get similar errors with any variable that is immediately adjacent to a code block inside a `TEXT` block.

**Comment by apizer** [comment]
This is not an old issue. It is new to WW2.18.  It breaks one of the oldest WW problems (Problem 2 in Set 0) but I thought the problem was corrupted and fixed it by accident.  I could not get the minimal problem above to work, but the following (please forgive my old technique) works in WW2.17 but fails in WW2.18.

DOCUMENT();
loadMacros("PGstandard.pl");
BEGIN_TEXT
Enter 1:
$BR\{ ans_rule(1) \}

END_TEXT
$ans =1;
ANS(std_num_cmp($ans));

ENDDOCUMENT();

**Comment by drgrice1** [comment]
This seems to be due to #863.  If you add a space in the TeX string on line 319 of PGbasicmacros.pl, then hardcopy generation succeeds.  However, it also adds a space in the output which is not desired.  This seems to be another case of EV3P parsing something in an odd way.

**Comment by Alex-Jordan** [comment]
Quick not that my MWEE was missing `MathObjects.pl`. 

```
DOCUMENT();
loadMacros("PGstandard.pl", "MathObjects.pl");
BEGIN_TEXT

$DOLLAR\{ ans_rule(1) \}

END_TEXT
ANS(Real(1)->cmp);
ENDDOCUMENT();
```

**Comment by drgrice1** [comment]
So what is happening is that `"<<END_OF_EVALUATION_STRING\n$DOLLAR{\\answerRule[AnSwEr0001]{3}}\nEND_OF_EVALUATION_STRING\n"` is being passed to `PG_restricted_eval` by the `EV3P` method.  So that is the perl code
```perl
<<END_OF_EVALUATION_STRING
$DOLLAR{\\answerRule[AnSwEr0001]{3}}
END_OF_EVALUATION_STRING
```
Perl is interpreting that to mean the hash key of the `%DOLLAR` hash indexed by `\\answerRule[AnSwEr0001]{3}`.  Since the `%DOLLAR` hash is not defined, it is an error.

**Comment by drgrice1** [comment]
Yeah, I added `MathObjects.pl`.

**Comment by drgrice1** [comment]
It seems that if you change line 319 to `TeX => "\\mbox{\\answerRule[$name]{$tcol}}"` it fixes the problem.  This seems like it should work.  Do you see any problems with that?  Note that all of the answer rule methods that add this `\\answerRule` in this way will need to be fixed.

**Comment by drgrice1** [comment]
Note that the `\\mbox` addition also works with `Library/Indiana/Indiana_setSeries5IntegralTest/ur_sr_5_11.pg` (the problem @pstaabp mentioned in #863 that results in the answer rule output being placed inside the option brackets of an `\item`.

**Comment by Alex-Jordan** [comment]
I'm not getting this to happen on develop. #915 and related PRs for develop fixed this.
